#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

src/Allwmake $targetType $*

wmake applications/solvers/reactingFoam
wmake applications/solvers/realFluidReactingFoam

#------------------------------------------------------------------------------
